# Generated by Django 2.2.1 on 2019-06-03 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PermissionsBlogSite', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mobileapp',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='mobileapptype',
            options={'managed': True},
        ),
    ]
