# Generated by Django 2.2.1 on 2019-06-03 13:09

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('PermissionsBlogSite', '0002_auto_20190603_1308'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mobileapp',
            options={},
        ),
        migrations.AlterModelOptions(
            name='mobileapptype',
            options={},
        ),
        migrations.CreateModel(
            name='MobileAppUserConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config', django.contrib.postgres.fields.jsonb.JSONField()),
                ('mobile_app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PermissionsBlogSite.MobileApp')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AppPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=200)),
                ('reason', models.TextField()),
                ('suggested', models.BooleanField(default=True)),
                ('suggested_reason', models.TextField()),
                ('mobile_app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PermissionsBlogSite.MobileApp')),
            ],
        ),
    ]
