# Generated by Django 2.2.1 on 2019-06-05 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PermissionsBlogSite', '0003_auto_20190603_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apppermissions',
            name='suggested',
            field=models.BooleanField(choices=[(True, 'On'), (False, 'Off')], default=True),
        ),
        migrations.AlterField(
            model_name='mobileapp',
            name='icon',
            field=models.ImageField(upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='mobileapp',
            name='type',
            field=models.ManyToManyField(related_name='mobileapps', to='PermissionsBlogSite.MobileAppType'),
        ),
    ]
