# Generated by Django 2.2.1 on 2019-06-08 07:34

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PermissionsBlogSite', '0011_auto_20190608_0731'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('platform', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=7), size=2), size=2)),
            ],
        ),
        migrations.AlterField(
            model_name='apppermissions',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PermissionsBlogSite.PermType'),
        ),
    ]
